/* Run: node tests/anime.test.cjs — no install, network or browser required. */
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
function load(storage){
  const context={window:{},localStorage:storage,console,setTimeout,clearTimeout};
  vm.createContext(context);
  for(const file of ['data.js','interests.js','anime-catalog.js','anime.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),context,{filename:file});
  return context.window;
}
const store=new Map();
const W=load({getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)});
const A=W.YOIN_ANIME,C=W.YOIN_ANIME_CATALOG,ids=W.YOIN_DATA.characters.map(c=>c.id);
assert.equal(C.titles.length,500);
assert.equal(new Set(C.titles.map(t=>t.id)).size,500);
assert(C.titles.every((t,i)=>t.rank===i+1&&/^tt\d+$/.test(t.id)&&t.signals.length===16&&t.signals.some(x=>x>0)&&t.signals.every(x=>Number.isFinite(x)&&x>=0&&x<=6)));
assert(C.titles.every((t,i)=>!i||C.titles[i-1].rating>=t.rating));
assert.equal(A.roles.length,8);
const cast=ids.slice(0,8);
assert(A.validCast(cast,true));
assert(!A.validCast(Array(8).fill(ids[0]),true));
assert(!A.validCast([...cast.slice(0,7),'unknown'],true));
assert.throws(()=>A.match(Array(8).fill(null)));
const swapped=A.assign(cast,0,cast[2]);
assert.equal(swapped[0],cast[2]);assert.equal(swapped[2],cast[0]);assert(A.validCast(swapped,true));
const empty=Array(8).fill(null);empty[0]=ids[0];const moved=A.assign(empty,3,ids[0]);assert.equal(moved[0],null);assert.equal(moved[3],ids[0]);
const first=A.match(cast),second=A.match(swapped);
assert.equal(first.ranked.length,500);
assert.equal(new Set(first.ranked.map(r=>r.id)).size,500);
assert.equal(first.top.length,3);
assert.equal(new Set(first.top.map(r=>A.family(A.titleById(r.id)))).size,3);
assert.notEqual(JSON.stringify(first.ranked.map(r=>r.score)),JSON.stringify(second.ranked.map(r=>r.score)));
assert.equal(JSON.stringify(first),JSON.stringify(A.match(cast)));
assert(first.ranked.every(r=>Number.isFinite(r.score)&&r.score>=0&&r.score<=100&&r.roles.length===8));
for(let i=0;i<100;i++)assert(A.validCast(A.shuffle(),true));
const completed={version:1,catalogVersion:C.version,cast,date:'2026-09-22T00:00:00Z'};
store.set('yoin:anime-result',JSON.stringify(completed));
store.set('yoin:result:chat-dna','{"untouched":true}');
assert(A.result().includes('另两条世界线'));
const svg=A.posterSVG(completed);
assert.equal((svg.match(/<image /g)||[]).length,8);
assert(svg.includes('data:image/'));assert(!svg.includes('undefined'));
assert(A.copyText(completed).includes('主角：'));assert(A.copyText(completed).includes('反派：'));
A.clear();assert.equal(store.get('yoin:result:chat-dna'),'{"untouched":true}');assert(!store.has('yoin:anime-result'));
const denied=load({getItem(){throw Error('blocked');},setItem(){throw Error('blocked');},removeItem(){throw Error('blocked');}}).YOIN_ANIME;
assert(denied.studio().includes('等待出演'));assert(denied.result().includes('开始选角'));assert.doesNotThrow(()=>denied.clear());
const corrupted=load({getItem(){return JSON.stringify({version:1,catalogVersion:1,cast:Array(8).fill('hxh'),active:99});}}).YOIN_ANIME;
assert(corrupted.studio().includes('等待出演'));assert(corrupted.result().includes('开始选角'));
console.log('PASS: 500 source entries, non-repeating casting, swapping, deterministic position-sensitive ranking, distinct-series top 3, saved result, offline poster, blocked/corrupt storage, old-test isolation.');
